In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr)

numpy.ndarray

In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3 = np.array([[[4,5,6],[8,8,8],[9,8,6]]])
arr3

array([[[4, 5, 6],
        [8, 8, 8],
        [9, 8, 6]]])

In [13]:
arr2.ndim

2

In [18]:
arr[3]

4

In [19]:
print(arr[3])

4


In [21]:
arr[0:3]

array([1, 2, 3])

In [25]:
arr2[0,0]

1

In [27]:
arr2[1,1]

5

In [29]:
arr3[0,1,2]

8

In [31]:
arr3.dtype

dtype('int32')

In [35]:
str1=np.array(['essfs','nfis','r','t'])
str1.dtype

dtype('<U5')

In [44]:
arr4 = np.array([23,12,34,45,56,50])
arr44 = arr4.copy()
arr44 
arr44[3] = 1000
arr44

array([  23,   12,   34, 1000,   56,   50])

In [48]:
arr4[4] = 199
arr4
arr44

array([  23,   12,   34, 1000,   56,   50])

In [49]:
arr5 = np.array([23,12,34,45,56,50])
y=arr5.copy()
y

array([23, 12, 34, 45, 56, 50])

In [50]:
arr5[1]=100
arr5.shape

array([ 23, 100,  34,  45,  56,  50])

In [51]:
y

array([23, 12, 34, 45, 56, 50])

In [60]:
arry = np.array([33,44,55,66,77,88])
v = arry.view()
v
v[2]=100
v
arry

array([ 33,  44, 100,  66,  77,  88])

In [62]:
arr5.shape

(6,)

In [64]:
arr2.shape

(2, 3)

In [66]:
arr3.shape

(1, 3, 3)

In [68]:
arr01 = np.array([3,54,2,3,5,34,2,1])
arr01.reshape(2,4)

array([[ 3, 54,  2,  3],
       [ 5, 34,  2,  1]])

In [71]:
arr02 = np.array([3,4,5,6,7,8,9,1,2,10,11,12])
arr02.reshape(1,4,3)

array([[[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9,  1,  2],
        [10, 11, 12]]])

In [75]:
e=np.array([2,34,4])
r=np.array([22,55,6])
conca = np.concatenate((e,r))
conca

array([ 2, 34,  4, 22, 55,  6])

In [80]:
u=np.array([[55,7,2],[2,34,4]])
i=np.array([[22,55,6],[4,5,6]])
conca = np.concatenate((i,u),axis=1)
conca

array([[22, 55,  6, 55,  7,  2],
       [ 4,  5,  6,  2, 34,  4]])

In [82]:
conca = np.concatenate((i,u),axis=0)
conca

array([[22, 55,  6],
       [ 4,  5,  6],
       [55,  7,  2],
       [ 2, 34,  4]])

In [86]:
stack = np.vstack((i,u))
stack

array([[22, 55,  6],
       [ 4,  5,  6],
       [55,  7,  2],
       [ 2, 34,  4]])

In [89]:
spl = np.array([111,333,444,666,777])
spl1 = np.array_split(spl,3)
spl1

[array([111, 333]), array([444, 666]), array([777])]

In [91]:
srt = np.array([300,87,5,65,1,23])
np.sort(srt)

array([  1,   5,  23,  65,  87, 300])

In [94]:
#linear algebra
arr1 = np.array([300,87,5,65,1,23])
arr2 = np.array([3,7,5,5,34,2])
result = np.dot(arr1,arr2)
result

1939

In [97]:
arr3 = np.array([[2,3,3],[3,4,5]])
arr4 = np.array([[55,6,7],[9,1,5]])
result = np.inner(arr3,arr4)
result

array([[149,  36],
       [224,  56]])

In [100]:
arr5 = np.array([[7,8,6],[3,4,5]])
arr6 = np.array([[11,12,23],[23,5,9]])
result = np.outer(arr5,arr6)
result

array([[ 77,  84, 161, 161,  35,  63],
       [ 88,  96, 184, 184,  40,  72],
       [ 66,  72, 138, 138,  30,  54],
       [ 33,  36,  69,  69,  15,  27],
       [ 44,  48,  92,  92,  20,  36],
       [ 55,  60, 115, 115,  25,  45]])

In [108]:
arr6 = np.array([[72,8],[37,40]])

res = np.linalg.det(arr6)
res

2583.999999999998

In [112]:
a=np.array([[1,2],[3,5]])
b=np.array([10,11])
solu = np.linalg.solve(a,b)
solu

array([-28.,  19.])

In [117]:
arr = np.array([[23,4],[4,5]])
sol = np.linalg.inv(arr)
sol

array([[ 0.05050505, -0.04040404],
       [-0.04040404,  0.23232323]])

In [145]:
array1 = np.array([1,2,3,4,5,6,7,8])
array4 = np.array([10,20,30,40,50,60,70,80])
array2 = np.array([[1,2,3],[4,5,6]])
array3 = np.array([[[4,5,6],[8,8,8],[9,8,6]]])
strarray = np.array(['a','b','ab','abc'])

In [121]:
type(array1)

numpy.ndarray

In [125]:
array3.ndim

3

In [127]:
array1[3:6]

array([4, 5, 6])

In [129]:
array2[1,2]

6

In [132]:
strarray.dtype

dtype('<U3')

In [134]:
array1copy = array1.copy()
array1copy

array([1, 2, 3, 4, 5, 6, 7])

In [137]:
array2view = array2.view()
array2view

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
array1.shape

(8,)

In [144]:
array1.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [149]:
con = np.concatenate((array1,array4))
con

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 20, 30, 40, 50, 60, 70, 80])

In [150]:
splt = np.array_split(array1,3)
splt

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [152]:
np.sort(strarray)

array(['a', 'ab', 'abc', 'b'], dtype='<U3')

In [154]:
np.dot(array1,array4)

2040

In [156]:
np.inner(array2,arr4)

array([[ 88,  26],
       [292,  71]])

In [158]:
np.outer(array2,arr4)

array([[ 55,   6,   7,   9,   1,   5],
       [110,  12,  14,  18,   2,  10],
       [165,  18,  21,  27,   3,  15],
       [220,  24,  28,  36,   4,  20],
       [275,  30,  35,  45,   5,  25],
       [330,  36,  42,  54,   6,  30]])

In [161]:
np.linalg.det(arr6)

2583.999999999998

In [163]:
np.linalg.inv(arr6)

array([[ 0.01547988, -0.00309598],
       [-0.01431889,  0.02786378]])